# Generated by Django 2.2.2 on 2020-01-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=125)),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_location', models.CharField(max_length=100)),
                ('event_category', models.CharField(choices=[('Shayari', 'Shayari'), ('Dance', 'Dance'), ('Music', 'Music'), ('Singing', 'Singing'), ('Photography', 'Photography'), ('Tiktok', 'Tiktok')], default='None', max_length=100, null=True)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_discription', models.TextField(blank=True, null=True)),
                ('event_address', models.TextField(blank=True, null=True)),
                ('event_instructuions', models.TextField(blank=True, null=True)),
                ('event_highlight1', models.TextField(blank=True, null=True)),
                ('event_highlight2', models.TextField(blank=True, null=True)),
                ('event_highlight3', models.TextField(blank=True, null=True)),
                ('event_highlight4', models.TextField(blank=True, null=True)),
                ('event_highlight5', models.TextField(blank=True, null=True)),
                ('event_highlight6', models.TextField(blank=True, null=True)),
                ('event_photo1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo7', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_sub_category', models.CharField(blank=True, max_length=80, null=True)),
                ('first_name', models.CharField(blank=True, max_length=125, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=125, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('alternamte_mobile', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_proof', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='identity_proof')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.event')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videos')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.event')),
                ('user_reg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.event')),
                ('user_reg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
    ]
