# Generated by Django 2.2.2 on 2019-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=125)),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_location', models.CharField(max_length=100)),
                ('event_category', models.CharField(choices=[('Shayari', 'Shayari'), ('dance', 'Dance'), ('music', 'Music'), ('singing', 'Singing'), ('drama', 'Drama')], default='None', max_length=100, null=True)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_discription', models.TextField(blank=True, null=True)),
                ('event_address', models.TextField(blank=True, null=True)),
                ('event_highlight1', models.TextField(blank=True, null=True)),
                ('event_highlight2', models.TextField(blank=True, null=True)),
                ('event_highlight3', models.TextField(blank=True, null=True)),
                ('event_highlight4', models.TextField(blank=True, null=True)),
                ('event_highlight5', models.TextField(blank=True, null=True)),
                ('event_highlight6', models.TextField(blank=True, null=True)),
                ('event_photo1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_photo7', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
