# Generated by Django 2.2.2 on 2019-12-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='user_registration',
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='user_reg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
