# Generated by Django 2.2.2 on 2019-12-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='event',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='user_reg',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
