# Generated by Django 2.2.2 on 2019-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
