# Generated by Django 2.2.2 on 2019-12-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='Last_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='alternamte_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='first_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='marital_status',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
