# Generated by Django 2.2.2 on 2019-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_remove_user_reg_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='registration_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
