# Generated by Django 2.2.2 on 2019-12-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_auto_20191222_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videos')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.event')),
                ('user_reg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.event')),
                ('user_reg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
    ]
