# Generated by Django 2.2.2 on 2019-12-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_auto_20191215_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('user_reg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
    ]
