# Generated by Django 2.2.2 on 2020-01-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_paytmhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user_reg',
        ),
    ]
