# Generated by Django 2.2.2 on 2019-12-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0003_images_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='id_prrof',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
