# Generated by Django 2.2.2 on 2020-01-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0003_remove_paytmhistory_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmhistory',
            name='user_reg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg'),
        ),
    ]
