# Generated by Django 2.2.2 on 2019-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0003_auto_20191203_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='event_category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='event_sub_category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
