# Generated by Django 2.2.2 on 2019-12-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videos')),
                ('user_registration', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_reg.user_reg')),
            ],
        ),
    ]
