# Generated by Django 2.2.2 on 2019-12-08 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_reg', '0003_auto_20191208_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='user_register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_payt', to=settings.AUTH_USER_MODEL),
        ),
    ]
