# Generated by Django 2.2.2 on 2019-12-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0004_user_reg_id_prrof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='id_prrof',
            new_name='id_proof',
        ),
    ]
