# Generated by Django 2.2.2 on 2019-12-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0004_user_reg_user_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='user_register',
            new_name='user',
        ),
    ]
