# Generated by Django 2.2.2 on 2020-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0005_auto_20191225_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_instructuions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
