# Generated by Django 2.2.2 on 2020-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0006_auto_20200123_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_images',
            name='image',
            field=models.ImageField(upload_to='temp_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='temp_videos',
            name='video',
            field=models.ImageField(upload_to='temp_videos/', verbose_name='Image'),
        ),
    ]
