# Generated by Django 2.2.2 on 2019-12-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0006_auto_20191215_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user_reg',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='PaytmHistory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_reg.PaytmHistory'),
        ),
    ]
