# Generated by Django 2.2.2 on 2019-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0007_auto_20191216_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Shayari', 'Shayari'), ('Dance', 'Dance'), ('Music', 'Music'), ('Singing', 'Singing'), ('Photography', 'Photography'), ('Tiktok', 'Tiktok')], default='None', max_length=100, null=True),
        ),
    ]
