# Generated by Django 2.2.2 on 2020-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0008_auto_20200129_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='other_instruction',
            new_name='other_instruction1',
        ),
        migrations.AddField(
            model_name='event',
            name='other_instruction2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_instruction3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_instruction4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_instruction5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
