# Generated by Django 2.2.2 on 2019-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0008_auto_20191217_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
