# Generated by Django 2.2.2 on 2020-02-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0009_auto_20200129_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='identity_proof_back',
            field=models.ImageField(blank=True, null=True, upload_to='identity_proof/', verbose_name='identity_proof'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to='identity_proof/', verbose_name='identity_proof'),
        ),
    ]
