# Generated by Django 2.2.2 on 2019-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0009_user_reg_identity_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='identity_proof'),
        ),
    ]
